CREATE TABLE NOTICE (

    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    WRITER VARCHAR(50) NOT NULL,
    FILE_NAME VARCHAR(255),
    FILE_ORIGIN_NAME VARCHAR(255),
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MOD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO NOTICE (TITLE, CONTENT, WRITER) VALUES ('첫 번째 공지사항입니다.', '공지사항 내용입니다.', 'admin');
